# ============================================================
#  VMD psfgen script — generated by prepare_motif.py
#  HackRush '26 | CHARMM36 topology generation
#  Input: 1GA7_B_301_GD3
#  Run via: vmd -dispdev text -e psfgen.tcl
# ============================================================

package require psfgen

# ------------------------------------------------------------
# 1. TOPOLOGY FILES
#    Set CHARMMDIR to the folder containing CHARMM36 RTF files.
#    Download from: http://mackerell.umaryland.edu/charmm_ff.shtml
# ------------------------------------------------------------
set CHARMMDIR "./charmm36"

topology $CHARMMDIR/top_all36_prot.rtf
topology $CHARMMDIR/toppar/toppar_water_ions.str
topology ./ln_custom.rtf   ;# custom Ln3+ topology

# ------------------------------------------------------------
# 2. PROTEIN SEGMENTS  (one per chain)
# ------------------------------------------------------------

segment PROB {
    pdb protein_B.pdb
    first NTER
    last  CTER
}
coordpdb protein_B.pdb PROB

# ------------------------------------------------------------
# 3. WATER SEGMENT
# ------------------------------------------------------------
segment SOLV {
    auto none
    pdb water.pdb
}
coordpdb water.pdb SOLV

# ------------------------------------------------------------
# 4. LANTHANIDE SEGMENT (GD3)
# ------------------------------------------------------------
segment LN01 {
    auto none
    pdb ions.pdb
}
coordpdb ions.pdb LN01

# ------------------------------------------------------------
# 6. GUESS MISSING COORDINATES (mainly added hydrogens)
# ------------------------------------------------------------
guesscoord

# ------------------------------------------------------------
# 7. WRITE OUTPUT FILES
# ------------------------------------------------------------
writepsf 1GA7_B_301_GD3_final.psf
writepdb 1GA7_B_301_GD3_final.pdb

puts "\n*** PSF generation complete ***"
puts "Output PSF : 1GA7_B_301_GD3_final.psf"
puts "Output PDB : 1GA7_B_301_GD3_final.pdb"
puts "Load in VMD: vmd 1GA7_B_301_GD3_final.pdb -psf 1GA7_B_301_GD3_final.psf"
